" Start with system default vimrc
if filereadable("/usr/share/vim/vimrc")
  source /usr/share/vim/vimrc
endif

" Set misc. UI options
set ruler               " Show line,col numbers in status line.
set showcmd             " Show (partial) command in status line.
set showmatch           " Show matching brackets.
set incsearch           " Incremental search
set number              " Show line numbers
set cursorline          " Highlight curser row
set wildmenu            " VIM CLI completion
set list lcs=tab:\|\ >  " Display tab as pipe (start) to > (end)

" Set smart indent by default
set autoindent
set smartindent

" Auto-select regexp engine
set regexpengine=0

" Load filetype-specific plugins and indents
filetype plugin indent on

" Auto match brace with new indented line
inoremap {<CR> {<CR>}<Esc>ko


" -- Plugins --


" Gruvbox colorscheme
set background=dark
let g:gruvbox_contrast_dark = 'hard'
let g:gruvbox_sign_column = 'bg0'
autocmd vimenter * ++nested colorscheme gruvbox
autocmd vimenter * ++nested syntax on

" Highlightedyank
let g:highlightedyank_highlight_duration = 150

" Gitgutter
set updatetime=100
